config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get 'signup', to: 'users/registrations#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :profiles
  end

  resources :podcasts do
    resource :episodes
  end

  get 'users/:user_id/studio' => 'studios#show', as: :studio

  get 'explore' => 'explores#index'
  get 'explore/search' => 'explores#index'

  delete 'podcasts/:podcast_id/episodes/:id' => 'episodes#destroy',  :as => :destroy_episode

  get 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#edit', :as => :update_episode

  patch 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#update'

  get '/users/:id' => 'users/registations#destroy', :via => :delete, :as => :destroy_user

  get 'users/:user_id/new' => 'profiles#new'
  root 'welcome#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_attached_file :avatar, styles: { large: '500x500>', medium: '300x300>', thumb: '100x100#' }, :default_url => ':rails_root/app/assets/images/default_thumb.jpg', :url => '/profiles/avatars/:id/:style/:basename.:extension', :path => ':rails_root/public/profiles/avatars/:id/:style/:basename.:extension'

  validates(:username, :presence => true, :length => { :maximum => 50 })
  validates(:first_name, :presence => true, :length => { :maximum => 50 })
  validates(:last_name, :presence => true, :length => { :maximum => 50 })
  validates(:portfolio_site, :presence => false, :length => { :maximum => 255 })
  validates(:twitter, :presence => false, :length => { :maximum => 255 })
  validates(:dribbble, :presence => false, :length => { :maximum => 255 })
  validates(:behance, :presence => false, :length => { :maximum => 255 })

  validates_attachment_content_type :avatar, :content_type => ['image/jpg', 'image/jpeg', 'image/png']

  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :check_for_profile, only: [:show]

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    if @profile.save
      flash[:notice] = 'Your profile has been created'
      redirect_to user_profiles_path(current_user)
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @profile = Profile.all
    @podcast = @user.podcasts.order(:created_at)
  end

  def edit
    @profile = Profile.find(params[:user_id])
  end

  def update
    @profile = Profile.find(current_user.id)

    if @profile.update(profile_params)
      flash[:notice] = 'Updated'
      redirect_to user_profiles_path(current_user)
    else
      puts @profile.errors.full_messages
      render :edit
    end
  end

  protected

  def check_for_profile
    if !current_user.profile
      flash[:alert] = "You need to create a profile"
      redirect_to new_user_profiles_path(current_user)
    end
  end

  def profile_params
    params.require(:profile).permit(:username, :first_name, :last_name, :portfolio_site, :twitter, :dribbble, :behance, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def full_name
    @profile = Profile.find(params[:user_id])
    @profile.first_name.capitalize + " " + @profile.last_name.capitalize
  end

  def current_user_full_name
    @profile = Profile.find(current_user.id)
    @profile.first_name.capitalize + " " + @profile.last_name.capitalize
  end
end

app/views/profiles/edit.html.haml
.page-new-wrapper
  = render 'partials/header'
  .page-create-body
    %h2 Update Profile
    = render 'partials/profile-form'

app/views/profiles/new.html.haml
.page-new-wrapper
  = render 'partials/header'
  .page-create-body
    %h2 your profile
    = render 'partials/profile-form'

app/views/profiles/show.html.haml
.profile-header
  = link_to root_path do
    = image_tag('nexus-icon.png', { class: 'icon-xs' })

  - if @user.id == current_user.id
    %h1 My Profile
  - else
    -if @user.profile
      %h1= full_name
    - else
      = @user.email

.profile-show-body
  - if @user.id == current_user.id
    %ul.quick-links
      %li= link_to 'Create Podcast', new_podcast_path
      %li= link_to 'Update Profile', edit_user_profiles_path(current_user)
      %li= link_to 'Cancel Account', destroy_user_path(current_user), :method => :delete, data: { confirm: 'Are you sure you want to cancel your account?' }

  .wrapper
    .profile-show-avatar
      - if @user.profile.avatar.exists?
        = image_tag(@user.profile.avatar.url(:thumb), { class: 'circle-img' })
      - else
        = image_tag('default_thumb', { class: 'circle-img' })
    %h2= full_name

    %h2 Podcasts
    %div
      - if @user.podcasts.exists?
        - @podcast.each do |p|
          = link_to p.title, podcast_path(p)
      - else
        %p No podcasts yet!