config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get 'signup', to: 'users/registrations#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :profiles
  end

  resources :podcasts do
    resource :episodes
  end

  get 'users/:user_id/studio' => 'studios#show', as: :studio

  get 'explore' => 'explores#index'
  get 'explore/search' => 'explores#index'

  delete 'podcasts/:podcast_id/episodes/:id' => 'episodes#destroy',  :as => :destroy_episode

  get 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#edit', :as => :update_episode

  patch 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#update'

  get '/users/:id' => 'users/registations#destroy', :via => :delete, :as => :destroy_user

  get 'users/:user_id/new' => 'profiles#new'
  root 'welcome#index'
end

app/views/partials/_episode-form.html.haml
= simple_form_for(@episode, url: podcast_episodes_path(@podcast), html: { class: 'info-form' }) do |f|
  .column#error_explanation
    = devise_error_messages(@episode)
    .column
      = f.input :episode_thumbnail, as: :file

    .column.form-inputs
      = f.input :title, name: 'title', :error => false, required: true, autofocus: true

    .column.form-inputs
      = f.input :description, name: 'description', :error => false, required: true, as: :text

    .column.form-inputs
      = f.input :keywords, name: 'keywords', :error => false

    .column
      = f.input :audio, as: :file
    .form-actions
      = f.button :submit, 'Create'

app/views/partials/_header.html.haml
%header.header
  .icon
    = link_to root_path do
      = image_tag('nexus-icon.png', { class: 'icon-xs' })
      = image_tag('nexus-labs-white.svg', { class: 'brand-xs' })

app/views/partials/_navbar.html.haml
.mobile-toggle.mobile-dark
  .line
  .line
  .line

%nav.navbar
  .navbar-header

    = image_tag('nexus-icon.png')
  - if user_signed_in?
    - if current_user.profile
      .profile-img.avatar-thumb-sm
        - if !current_user.profile.avatar
          = image_tag('deault_thumb.jpg')
        - else
          = image_tag current_user.profile.avatar.url(:thumb)
        %h3= current_user_full_name


    .profile-links
      %h3.nav-title My Account
      %ul.nav-links
        %li{:class => active_route?(user_profiles_path(current_user))}= link_to 'Profile', user_profiles_path(current_user)
        %li= link_to 'Settings'
        %li= link_to 'Logout', destroy_user_session_path, :method => :delete

  - else
    =link_to 'Log In', login_path
  .company-links
    %h3.nav-title Nexus Labs
    %ul.nav-links
      %li{:class => active_route?(root_path)}= link_to "Home", root_path
      %li{:class => active_route?(explore_path)}= link_to 'Explore', explore_path
      %li= link_to 'Pricing'

app/views/partials/_podcast-form.html.haml
= simple_form_for @podcast,  class: 'info-form'  do |f|
  .column#error_explanation
    = devise_error_messages(@podcast)
  .column
    .column.hor-center
      = f.input :podcast_thumbnail, as: :file

    .column.form-inputs
      = f.input :title, name: 'title', :error => false, required: true, autofocus: true

    .column.form-inputs
      = f.input :description, name: 'description', :error => false, required: true, as: :text

    .column.form-inputs
      = f.input :owner, name: 'podcast_owner', :error => false, required: true, :input_html => { :value => current_user_full_name }

    .column.form-inputs
      = f.input :manager, name: 'manager', :error => false

    .column.form-inputs
      = f.input :keywords, name: 'keywords', :error => false

    .form-actions
      = f.button :submit, 'Create'

app/views/partials/_profile-form.html.haml
= simple_form_for([@user, @profile], as: @profile, url: user_profiles_path([@user, @profile]), html: { class: 'info-form' }) do |f|
  .column#error_explanation
    = devise_error_messages(@profile)
  .column.hor-center
    = f.input :avatar, as: :file
  .column
    .column.form-inputs
      = f.input :username, name: 'username', :error => false, required: true, autofocus: true

    .row
      .column.form-inputs
        = f.input :first_name, name: 'first name', :error => false, :required => true

      .column.form-inputs
        = f.input :last_name, name: 'last night', :error => false,
        :required => true

    .column.form-inputs
      = f.input :portfolio_site, name: 'portfolio site', :error => false

    .row
      .column.form-inputs
        = f.input :twitter, name: 'twitter', :error => false

      .column.form-inputs
        = f.input :dribbble, name: 'dribbble', :error => false

    .column.form-inputs
      = f.input :behance, name: 'behance', :error => false
  .form-actions

    = f.button :submit, 'Create'

app/views/partials/_search-form.html.haml
.search-bar
  = search_form_for @q, url: @search_path do |f|
    = f.search_field :title_cont, placeholder: 'Search'
    .search-action
      = f.submit '', :name => nil

app/views/partials/_user-form.html.haml
= simple_form_for(@user, as: @user, url: registration_path(@user), html: { class: 'info-form' }) do |f|
  .column#error_explanation
    = devise_error_messages(@user)
  .column
    .column.form-inputs
      = f.input :email, name: 'email', :error => false, required: true, autofocus: true

    .column.form-inputs

      = f.input :password, name: 'password', :error => false, required: true, hint: ("8 characters minimum")

    .column.form-inputs

      = f.input :password_confirmation, :error => false, name: 'password_confirmation', required: true
  .form-actions
    = f.button :submit, "Sign up"
= render "devise/shared/links"

app/views/partials/_user-search-form.html.haml
.search-bar
  = search_form_for @q, url: user_profiles_path do |f|
    = f.search_field :first_name_cont, placeholder: 'Search'
    .search-action
      = f.submit '', :name => nil