config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get 'signup', to: 'users/registrations#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :profiles
  end

  resources :podcasts do
    resource :episodes
  end

  get 'users/:user_id/studio' => 'studios#show', as: :studio

  get 'explore' => 'explores#index'
  get 'explore/search' => 'explores#index'

  delete 'podcasts/:podcast_id/episodes/:id' => 'episodes#destroy',  :as => :destroy_episode

  get 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#edit', :as => :update_episode

  patch 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#update'

  get '/users/:id' => 'users/registations#destroy', :via => :delete, :as => :destroy_user

  get 'users/:user_id/new' => 'profiles#new'
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
#welcome
  .column
    %span.brand
      = image_tag('nexus-icon.png',  class: 'icon-r')
      = image_tag('nexus-labs-white.svg', class: 'brand-r')
  .tagline.col-9
    %p Nexus Labs is a podcasting platform that allows you to record simultaneous audio from all users within your Studio. Nexus Labs aims to make it easier for you to conduct your profession by making it easier to have conversations with others
  %span.action-buttons
    = link_to 'Explore', explore_path, { class: 'btn btn-green no-decoration' }
    = link_to 'Sign Up', signup_path, { class: 'btn btn-blue no-decoration' }

.features.column.container.center
  %h1 Features

  %ul.feature-list
    %li.col-3
      = image_tag('group.svg')
      %p Multi-user studio rooms to record group audio
    %li.col-3
      = image_tag('search.svg')
      %p Explore other podcasts and discover great content
    %li.col-3
      = image_tag('upload.svg')
      %p Host your podcasts on a custom website with your own domain