config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    get 'signup', to: 'users/registrations#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  resources :users do
    resource :profiles
  end

  resources :podcasts do
    resource :episodes
  end

  get 'users/:user_id/studio' => 'studios#show', as: :studio

  get 'explore' => 'explores#index'
  get 'explore/search' => 'explores#index'

  delete 'podcasts/:podcast_id/episodes/:id' => 'episodes#destroy',  :as => :destroy_episode

  get 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#edit', :as => :update_episode

  patch 'podcasts/:podcast_id/episodes/:id/edit' => 'episodes#update'

  get '/users/:id' => 'users/registations#destroy', :via => :delete, :as => :destroy_user

  get 'users/:user_id/new' => 'profiles#new'
  root 'welcome#index'
end

app/models/podcast.rb
class Podcast < ApplicationRecord


  belongs_to :user
  has_many :episodes, dependent: :destroy

  accepts_nested_attributes_for :episodes

  has_attached_file :podcast_thumbnail, styles: { x_large: '1920x940>', medium: '250x250#', thumb: '150x150#' }, :default_url => ':rails_root/public/podcast/defaults/:style/default.jpg', :url => '/podcast/thumb/:id/:style/:basename.:extension', :path => ':rails_root/public/podcast/thumb/:id/:style/:basename.:extension'

  validates_attachment_content_type :podcast_thumbnail, :content_type => ['image/jpg', 'image/jpeg', 'image/png']

  validates(:title, :presence => true, :length => { :maximum => 50 })
  validates(:description, :presence => true)

  validates_with AttachmentSizeValidator, attributes: :podcast_thumbnail, less_than: 3.megabytes


end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index

  end
  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)
    @podcast.user_id = current_user.id

    if @podcast.save
      flash[:notice] = "Podcast Created!"
      redirect_to podcast_path(@podcast)
    else
      flash[:alert] = "Something went wrong. Try again."
      render :new
    end
  end

  def show
    @podcast = Podcast.find(params[:id])
    @episode = @podcast.episodes.all
    @q = @episode.ransack(params[:q])
    @episode = @q.result

    @search_path = ""
  end

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])
    if @podcast.update(podcast_params)
      flash[:notice] = 'Podcast updated'
      redirect_to podcast_path
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def destroy
    @podcast = Podcast.find(params[:id])

    if @podcast.destroy
      flash[:notice] = "Your podcast has been deleted"
      redirect_to user_profiles_path(current_user)
    end
  end
  protected

  def podcast_params
    params.require(:podcast).permit(:title, :podcast_thumbnail, :description, :owner, :manager, :keywords)
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/edit.html.haml
.page-new-wrapper
  = render 'partials/header'
  .page-create-body
    = render 'partials/podcast-form'

app/views/podcasts/new.html.haml
.page-new-wrapper
  = render 'partials/header'
  .page-create-body
    = render 'partials/podcast-form'

app/views/podcasts/show.html.haml
.podcast-page
  = render 'partials/header'
  .after-img
    - if @podcast.podcast_thumbnail.exists?
      = image_tag @podcast.podcast_thumbnail.url(:x_large), class: 'cover-photo'
    - else
      = image_tag('default_x_large.jpg')


  .podcast-header
    .podcast-title
      %h1.col-5= @podcast.title
      %p.font-green= @podcast.keywords

.podcast-sub-header
  .container.row.center
    .action-button
      = button_to("Follow", nil, { class: 'btn btn-green'})

    = render 'partials/search-form'

    .podcast-stats.row
      .column
        %p Followers
        %p.number 15K
      .column
        %p Following
        %p.number 10
      .column
        %p Episodes
        %p.number= @podcast.episodes.count

.podcast-body
  - if user_signed_in?
    - if @podcast.user_id == current_user.id
      %ul.quick-links
        %li= link_to 'Create Episode', new_podcast_episodes_path(@podcast)
        %li= link_to 'Update Podcast', edit_podcast_path
        %li= link_to 'Delete Podcast', podcast_path(@podcast), :method => :delete, data: { confirm: 'Are you sure you want to delete this podcast?' }
  .container.center.podcast-owner
    %h2.text-center Authors
    = image_tag @podcast.user.profile.avatar.url(:thumb)
    %p.owner= @podcast.owner

    - if !@podcast.manager.empty?
      %h2 Managers
      %p= @podcast.manager
    %p.podcast-description= @podcast.description

  - @episode.each do |e|
    .container.center
      .episode
        .episode-img
          - if !e.episode_thumbnail.exists?
            = image_tag e.podcast.podcast_thumbnail.url(:thumb)
          - else
            = image_tag e.episode_thumbnail.url(:thumb)
        .episode-body
          %h2.ep-title= e.title
          %p.ep-date
          %p.ep-description= e.description
          %p.audio-url
            = audio_tag(e.audio.url, controls: true)
          %p.created-at
            Published:
            = e.created_at.strftime("%B, %e, %G")
          - if user_signed_in?
            - if @podcast.user_id == current_user.id
              = link_to 'Delete Episode', destroy_episode_path(e), :method => :delete, data: { confirm: 'Are you sure you want to delete this podcast?' }, class: 'btn btn-red'
              = link_to 'Update Episode', update_episode_path(@podcast, e), class: 'btn btn-amber'